---
title: "Week9_codealong_challenge"
author: "Chen Junyu Ryan"
date: "2023-10-18"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

#TIDYDATA

```{r,eval=TRUE,echo=TRUE}
tidydata <- tribble(
  ~country, ~year, ~cases, ~population,
  "Afghanistan", 1999, 745, 19987071,
  "Afghanistan", 2000, 2666, 20595360,
  "Brazil", 1999, 37737, 172006362,
  "Brazil", 2000, 80488, 174504898,
  "China", 1999, 212258, 1272915272,
  "China", 2000, 213766, 1280428583
)
```

```{r,eval=TRUE,echo=TRUE}
nontidydata <- tribble(
  ~country, ~year, ~rate,
  "Afghanistan", 1999, "745/19987071",
  "Afghanistan", 2000, "2666/20595360",
  "Brazil", 1999, "37737/172006362",
  "Brazil", 2000, "80488/174504898",
  "China", 1999, "212258/1272915272",
  "China", 2000, "213766/1280428583"
)

nontidydata
```

```{r,eval=TRUE,echo=TRUE}
tidydata %>%
 group_by(year) %>%
 summarize(total_cases = sum(cases))
```

```{r,eval=TRUE,echo=TRUE}
tidieddata <- nontidydata %>%
 separate(rate, into = c("cases",
 "population"),
 sep = "/")
tidieddata
```

```{r,eval=TRUE,echo=TRUE}
newtidieddata <- tidieddata %>%
 pivot_longer(
 cols = cases:population,
 names_to = "measurement",
 values_to = "value"
 )
newtidieddata
```

```{r,eval=TRUE,echo=TRUE}
ggplot(newtidieddata) +
 aes(x=year,y=value, colour=country) +
 geom_point() +
 geom_line(aes(group = country))+
 facet_wrap(~measurement) +
 theme_bw()
```

```{r,eval=TRUE,echo=TRUE}
df <- tribble(
 ~id, ~bp1, ~bp2,
 "A", 100, 120,
 "B", 140, 115,
 "C", 120, 125
)
df
```

```{r,eval=TRUE,echo=TRUE}
df %>%
 pivot_longer(
 cols = bp1:bp2,
 names_to = "measurement",
 values_to = "value"
 )
```

```{r,eval=TRUE,echo=TRUE}
newtidieddata %>%
 pivot_wider(names_from="measurement",
 values_from="value")
```

```{r,eval=TRUE,echo=TRUE}
df <- tribble(
 ~id, ~measurement, ~value,
 "A", "bp1", 100,
 "B", "bp1", 140,
 "B", "bp2", 115,
 "A", "bp2", 120,
 "A", "bp3", 105
)
df
```


```{r,eval=TRUE,echo=TRUE}
df %>%
 pivot_wider(
 names_from = measurement,
 values_from = value
 )

```

```{r,eval=TRUE,echo=TRUE}
library(rvest)
webpage <- read_html("https://books.toscrape.com/")
table <-html_elements(webpage,"body")
```

```{r,eval=TRUE,echo=TRUE}
library(httr)
library(jsonlite)
```

```{r,eval=TRUE,echo=TRUE}
# current data
current_county_data_url <- "https://api.covidactnow.org/v2/counties.csv?apiKey=YOUR_KEY_HERE"
# historic data
historic_county_data_url <-
"https://api.covidactnow.org/v2/counties.timeseries.csv?apiKey=YOUR_KEY_HERE"
# individual location data
individual_loc_data_url <-
"https://api.covidactnow.org/v2/county/{state}.csv?apiKey=YOUR_KEY_HERE"

```

```{r,eval=FALSE,echo=TRUE}
# current data
current_county_data_url <- "https://api.covidactnow.org/v2/counties.csv?apiKey=33382de96fd8441fb6c"
raw_data <- GET(current_county_data_url)
raw_data$status
raw_data$content
```

```{r,eval=FALSE,echo=TRUE}
# current data
current_county_data_url <- "https://api.covidactnow.org/v2/counties.csv?apiKey=33382de96fd8441fb6c"
raw_data <- GET(current_county_data_url)
raw_data$status
raw_data$content
```

```{r,eval=FALSE,echo=TRUE}
# historic data
historic_county_data_url <-
"https://api.covidactnow.org/v2/counties.timeseries.csv?apiKey=33382de96fd8441fb6c1eca82b3bd4ec"
raw_data <- GET(historic_county_data_url)
raw_data$status
raw_data$content
```

```{r,eval=FALSE,echo=TRUE}
# individual location data
individual_loc_data_url <-
"https://api.covidactnow.org/v2/county/{49}.csv?apiKey=33382de96fd8441fb6c1eca82b3bd4ec"
raw_data <- GET(individual_loc_data_url)
raw_data$status
raw_data$content
```
```{r,eval=TRUE,echo=TRUE}
billboard
week <- billboard %>%
  pivot_longer(cols = starts_with("wk"), 
names_to ="week",      
values_to = "value",
values_drop_na = TRUE) %>%
  mutate(week = parse_number(week))

ggplot(week, aes(x = week, y = value, group=track)) +
  geom_line() +
  labs(x = "week", y = "rank") +
  ggtitle("rank vs. week") +
  theme_minimal()
```
```{r,eval=TRUE,echo=TRUE}
cms_patient_experience
cms_patient_experience %>% 
pivot_wider(names_from = "measure_cd", values_from=  "prf_rate",id_cols = starts_with("org"))
```