---
title: "Challenge week 7"
author: "Chen Junyu Ryan"
date: "2023-10-04"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=TRUE, eval=TRUE}
library(tidyverse)
library(palmerpenguins)
glimpse(penguins)
```

```{r echo=TRUE, eval=TRUE}
ggplot(data = penguins,
 mapping = aes(x = bill_depth_mm,
 y = bill_length_mm,
 colour = species)) +
 geom_point() +
 labs(title = "Bill depth and length",
 subtitle = "Dimensions for Adelie, Chinstrap",
 x = "Bill depth (mm)", y = "Bill length (mm)",
 colour = "Species",
caption = "Source: Palmer Station LTER") +
 scale_colour_viridis_d()

#a. Start with the penguins data frame,
#b. Map bill depth to the x-axis
#c. Map bill length to the y-axis
#d. Represent each observation with a point
#e. Map species to the colour of each point
#f. Title the plot "Bill depth and length"
#g. Add the subtitle "Dimensions for Adelie, Chinstrap, and Gentoo Penguins"
#h. Label the x and y axes as "Bill depth (mm)" and "Bill length (mm)", respectively
#i. Label the legend "Species"
#j. Add a caption for the data source
#k. Finally, use a discrete colour scale that is designed to be
```
```{r echo=TRUE, eval=TRUE}
#You can omit the names of first two arguments when building plots with ggplot()

ggplot(penguins,
 aes(x = bill_depth_mm,
 y = bill_length_mm,
 colour = species)) +
 geom_point() +
 scale_colour_viridis_d()
```
```{r echo=TRUE, eval=TRUE}
#Palmer Penguins: Colour
ggplot(penguins) + aes(x = bill_depth_mm, y = bill_length_mm,
 colour = species) +
 geom_point() + scale_colour_viridis_d()
```
```{r echo=TRUE, eval=TRUE}
#Palmer Penguins: Shape
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species,
 shape = island)) +
 geom_point() + scale_colour_viridis_d()
```

```{r echo=TRUE, eval=TRUE}
#Palmer Penguins: Shape
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species,
 shape = species)) +
 geom_point() + scale_colour_viridis_d()
```


```{r echo=TRUE, eval=TRUE}
#Palmer Penguins: Size
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species, shape = species,
 size = body_mass_g)) +
 geom_point() + scale_colour_viridis_d()
```
```{r echo=TRUE, eval=TRUE}
#Palmer Penguins: Alpha
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species,
 shape = species, size = body_mass_g, alpha = flipper_length_mm)) +
 geom_point() + scale_colour_viridis_d()
```

#Mapping: Determine the size, alpha, etc. of points based on the values of a variable in the data goes into aes()
#Setting: Determine the size, alpha, etc. of points not based on the values of a variable in the data goes into geom_*() (this was geom_point() in the previous example, but we'll learn about other geoms soon!)

```{r echo=TRUE, eval=TRUE}
#Palmer Penguins: MAPPING
ggplot(penguins) +
 aes(x = bill_depth_mm,
 y = bill_length_mm,
 size = body_mass_g,
 alpha = flipper_length_mm) +
 geom_point()
```

```{r echo=TRUE, eval=TRUE}
#Palmer Penguins: SETTING
ggplot(penguins) +
 aes(x = bill_depth_mm,
 y = bill_length_mm) +
 geom_point(size = 2, alpha = 0.5)
```
```{r echo=TRUE, eval=TRUE}
#Palmer Penguins: Faceting Useful for exploring conditional relationships and large data
ggplot(penguins) +
 aes(x = bill_depth_mm,
 y = bill_length_mm) +
 geom_point() +
 facet_grid(species ~ island)
```

```{r echo=TRUE, eval=TRUE}
#Palmer Penguins: Faceting 2 
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_grid(species ~ sex)
```

```{r echo=TRUE, eval=TRUE}
#Palmer Penguins: Faceting 3
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_grid(sex ~ species)
```

```{r echo=TRUE, eval=TRUE}
#Palmer Penguins: Faceting 4
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_wrap(~ species)
```
```{r echo=TRUE, eval=TRUE}
#Palmer Penguins: Faceting 5
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_wrap(~ species, ncol = 2)
```

```{r echo=TRUE, eval=TRUE}
#Palmer Penguins: Faceting 6
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_grid(. ~ species)
```

```{r echo=TRUE, eval=TRUE}
#Face and color, no legend
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +
 geom_point() + facet_grid(species ~ sex) + scale_color_viridis_d() +
 guides(color = "none")
```

```{r echo=TRUE, eval=TRUE}
#Take a peek at data
library(openintro)
glimpse(loans_full_schema)
```

```{r echo=TRUE, eval=TRUE}
#selected variables
loans <- loans_full_schema %>%
 select(loan_amount, interest_rate, term, grade,
 state, annual_income, homeownership, debt_to_income)
glimpse(loans)
```

```{r echo=TRUE, eval=TRUE}
#Histogram
ggplot(loans) + aes(x = loan_amount) +
 geom_histogram()
```

```{r echo=TRUE, eval=TRUE}
#Histograms and binwidth=1000
# binwidth = 1000
ggplot(loans, aes(x = loan_amount)) +
 geom_histogram(binwidth = 1000)

```

```{r echo=TRUE, eval=TRUE}
#Histograms and binwidth = 5000
# binwidth = 5000
ggplot(loans, aes(x = loan_amount)) +
 geom_histogram(binwidth = 5000)

```

```{r echo=TRUE, eval=TRUE}
#Histograms and binwidth=20000
# binwidth = 20000
ggplot(loans, aes(x = loan_amount)) +
 geom_histogram(binwidth = 20000)

```

```{r echo=TRUE, eval=TRUE}
#Customizing histograms
ggplot(loans, aes(x = loan_amount)) + geom_histogram(binwidth = 5000) +
 labs(x = "Loan amount ($)", y = "Frequency", title = "Amounts of Lending Club loans" )
```

```{r echo=TRUE, eval=TRUE}
#Fill with a categorical variable
ggplot(loans, aes(x = loan_amount, fill = homeownership)) +
 geom_histogram(binwidth = 5000, alpha = 0.5) +
 labs(x = "Loan amount ($)",y = "Frequency",title = "Amounts of Lending Club loans")
```

```{r echo=TRUE, eval=TRUE}
#Facet with a categorical variable
ggplot(loans, aes(x = loan_amount, fill = homeownership)) + geom_histogram(binwidth = 5000) +
 labs(x = "Loan amount ($)",y = "Frequency",title = "Amounts of Lending Club loans") +
 facet_wrap(~ homeownership, nrow = 3)
```

```{r echo=TRUE, eval=TRUE}
#Density plot
ggplot(loans, aes(x = loan_amount)) +
 geom_density()
```

```{r echo=TRUE, eval=TRUE}
#Density plots and adjusting bandwidth
ggplot(loans, aes(x = loan_amount)) +
 geom_density(adjust = 0.5)
```

```{r echo=TRUE, eval=TRUE}
#Density plots and adjusting bandwidth
ggplot(loans, aes(x = loan_amount)) +
 geom_density(adjust = 1) # default bandwidth
```

```{r echo=TRUE, eval=TRUE}
#Density plots and adjusting bandwidth
ggplot(loans, aes(x = loan_amount)) +
 geom_density(adjust = 2)
```

```{r echo=TRUE, eval=TRUE}
#Customizing density plots
ggplot(loans, aes(x = loan_amount)) +
 geom_density(adjust = 2) +
 labs( x = "Loan amount ($)", y = "Density", title = "Amounts of Lending Club loans" )

```

```{r echo=TRUE, eval=TRUE}
#Adding a categorical variable
ggplot(loans, aes(x = loan_amount, fill = homeownership)) +
 geom_density(adjust = 2, alpha = 0.5) +
 labs(x = "Loan amount ($)",y = "Density",title = "Amounts of Lending Club loans", fill = "Homeownership")
```
```{r echo=TRUE, eval=TRUE}
#Box Plot
ggplot(loans, aes(x = interest_rate)) +
 geom_boxplot()
```
```{r echo=TRUE, eval=TRUE}
#Box plot and outliers
ggplot(loans, aes(x = annual_income)) +
 geom_boxplot()
```

```{r echo=TRUE, eval=TRUE}
#Customizing box plots
ggplot(loans, aes(x = interest_rate)) +geom_boxplot() +labs(x = "Interest rate (%)",y = NULL,
 title = "Interest rates of Lending Club loans") +
 theme( axis.ticks.y = element_blank(), axis.text.y = element_blank() )
```

```{r echo=TRUE, eval=TRUE}
#Adding a categoric variable
ggplot(loans, aes(x = interest_rate,
 y = grade)) +
 geom_boxplot() +
 labs(x = "Interest rate (%)",y = "Grade",title = "Interest rates of Lending Club loans",subtitle="Source")
```
```{r echo=TRUE, eval=TRUE}
#Scatterplot
ggplot(loans, aes(x = debt_to_income, y = interest_rate)) +
 geom_point()
```
```{r echo=TRUE, eval=TRUE}
#Hex plot
ggplot(loans, aes(x = debt_to_income, y = interest_rate)) +
 geom_hex()
```

```{r echo=TRUE, eval=TRUE}
#Hex plot
ggplot(loans %>% filter(debt_to_income < 100),
 aes(x = debt_to_income, y = interest_rate)) +
 geom_hex()
```
```{r echo=TRUE, eval=TRUE}
#Bar plot
ggplot(loans, aes(x = homeownership)) +
 geom_bar()
```

```{r echo=TRUE, eval=TRUE}
#Segmented bar plot
ggplot(loans, aes(x = homeownership,
 fill = grade)) +
 geom_bar()
```

```{r echo=TRUE, eval=TRUE}
#Segmented bar plot
ggplot(loans, aes(x = homeownership, fill = grade)) +
 geom_bar(position = "fill")
```
```{r echo=TRUE, eval=TRUE}
#Customizing bar plots
ggplot(loans, aes(y = homeownership, fill = grade)) + geom_bar(position = "fill") +
labs( x = "Proportion", y = "Homeownership", fill = "Grade", title = "Grades of Lending Club loans")
```

```{r echo=TRUE, eval=TRUE}
#Violin plots
ggplot(loans, aes(x = homeownership, y = loan_amount)) +
 geom_violin()
```

```{r echo=TRUE, eval=TRUE}
#Ridge plots
library(ggridges)
ggplot(loans, aes(x = loan_amount, y = grade, fill = grade, color = grade)) +
 geom_density_ridges(alpha = 0.5)
```

